spring.application.name=CustomerService

spring.config.import=consul:

spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500

spring.cloud.consul.config.enabled=true
spring.cloud.consul.config.format=PROPERTIES

spring.cloud.openfeign.micrometer.enabled=true
otel.propagators=tracecontext,baggage
